# -*- coding: utf-8 -*-
"""cube.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QMqoARY-AY0M7XzSEHyAb3kQHFU9zdbP
"""

def sumOfSeries(n): 
    sum = 0
    for i in range(1, n+1): 
        sum +=i*i*i 
          
    return sum
  
   
# Driver Function 
n = 5
print(sumOfSeries(n))