# -*- coding: utf-8 -*-
"""multiple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QMqoARY-AY0M7XzSEHyAb3kQHFU9zdbP
"""



list1 = [11, 5, 17, 18, 23, 50]  
  
# Iterate each element in list 
# and add them in variale total 
for ele in list1: 
    if ele % 2 == 0: 
        list1.remove(ele) 
  
# printing modified list 
print("New list after removing all even numbers: ", list1)